### ISSUE TITLE
ERROR con pip install -r requirements.txt

### ISSUE THREAD

**Issue by Marzal** [educollado/rss_podcast_generator#1]
Buenas Eduardo.

¿El requirements.txt lo has creado con pip freeze?

No me va bien la preparación de las dependencias, porque mi pip 20.2.1 no acepta el formato el fichero.
https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

**Comment by educollado** [comment]
Pues la verdad es que no, déjame ver esto y actualizo.

Mil gracicas

**Comment by educollado** [comment]
Ya debería de estar arreglado.

Un saludo

**Comment by educollado** [comment]
Cierro

**Comment by Marzal** [comment]
Ya he tenido un rato, si que funciona con el cambio :+1:  . Gracias!

Te pongo otro issues con algunas cosas que he visto :wink:
